In [1]:
import pandas as pd

In [2]:
df = pd.read_json('test.json')

In [4]:
df.head()

,"('AUD', 'Long_Only')","('AUD', 'MACD')","('AUD', 'Trend')","('AUD', 'Linear_OLS')","('AUD', 'Linear_Custom')","('AUD', 'LightGBM')","('AUD', 'LightGBM_Custom')","('COPPER', 'Long_Only')","('COPPER', 'MACD')","('COPPER', 'Trend')","('COPPER', 'Linear_OLS')","('COPPER', 'Linear_Custom')","('COPPER', 'LightGBM')","('COPPER', 'LightGBM_Custom')"
2004-01-08,0.005564,0.005564,0.005564,0.005564,0.005564,0.005564,0.005564,-0.002871,-0.002871,-0.002871,-0.002871,-0.002871,0.002871,0.002871
2004-01-09,0.002192,0.002192,0.002192,-0.002192,-0.002192,0.002192,0.002192,-0.011499,-0.011499,-0.011499,-0.011499,-0.011499,0.011499,-0.011499
2004-01-12,0.000564,0.000564,0.000564,0.000564,-0.000564,0.000564,-0.000564,0.001710,0.001710,0.001710,0.001710,-0.001710,-0.001710,0.001710
2004-01-13,-0.004238,-0.004238,-0.004238,-0.004238,-0.004238,-0.004238,-0.004238,0.005027,0.005027,0.005027,0.005027,0.005027,-0.005027,-0.005027
2004-01-14,-0.012939,-0.012939,-0.012939,-0.012939,-0.012939,-0.012939,0.012939,-0.005990,-0.005990,-0.005990,-0.005990,0.005990,0.005990,-0.005990

In [5]:
df.loc[:,df.columns.str.contains('Only')]

            ('AUD', 'Long_Only')  ('COPPER', 'Long_Only')
2004-01-08              0.005564                -0.002871
2004-01-09              0.002192                -0.011499
2004-01-12              0.000564                 0.001710
2004-01-13             -0.004238                 0.005027
2004-01-14             -0.012939                -0.005990
...                          ...                      ...
2019-12-24              0.002304                 0.000000
2019-12-25              0.008269                 0.011901
2019-12-26              0.013656                -0.011580
2019-12-27              0.008056                -0.002579
2019-12-30              0.002934                -0.009528

[4153 rows x 2 columns]